services:
    frontend:
        build:
            dockerfile: Dockerfile
        container_name: frontend
        restart: unless-stopped
        ports:
            - "${PORT_GATEWAY}:80"
        environment:
            - DEBUG=${DEBUG}
        # volumes:
        #     - ./public:/var/www/html
